<?php

/**
 *  @file
 *  The Views Slideshow: menu adds a menu slideshow mode to Views Slideshows.
 */

/**
 *  Implements hook_theme().
 */
function views_slideshow_menu_theme($existing, $type, $theme, $path) {
  return array(
    'views_slideshow_menu' => array(
      'arguments' => array('view' => NULL, 'options' => array(), 'rows' => array(), 'title' => ''),
      'template' => 'views-slideshow-menu',
      'file' => 'views_slideshow_menu.theme.inc',
    ),
    'views_slideshow_menu_no_display_section' => array(
      'arguments' => array('view' => NULL, 'rows' => NULL, 'id' => NULL, 'mode' => NULL, 'teaser' => TRUE),
      'file' => 'views_slideshow_menu.theme.inc',
    ),
    'views_slideshow_menu_no_display_teaser' => array(
      'arguments' => array('item' => NULL, 'id' => NULL, 'count' => NULL),
      'file' => 'views_slideshow_menu.theme.inc',
    ),
  );
}